import { style } from "@vanilla-extract/css";

export const reactFetchDevtoolsObserveAndMockContainerCss = {
  callButton: style({
    ":hover": {
      borderColor: "#ff0558",
      color: "#ff0558",
    },
    background: "#ffffff",
    border: "1px solid #ff8ab2",
    borderRadius: 999,
    color: "#c90045",
    cursor: "pointer",
    font: "inherit",
    fontSize: 14,
    fontWeight: 700,
    padding: "7px 14px",
  }),
  callRow: style({
    display: "flex",
    flexWrap: "wrap",
    gap: 12,
    justifyContent: "center",
  }),
  resultBody: style({
    background: "#fff1f5",
    border: "1px solid rgb(255 5 88 / 0.18)",
    borderRadius: 8,
    color: "#111827",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: 12,
    lineHeight: 1.6,
    margin: 0,
    maxHeight: 160,
    overflow: "auto",
    padding: 12,
    whiteSpace: "pre-wrap",
    wordBreak: "break-all",
  }),
  resultCard: style({
    background: "#ffffff",
    border: "2px solid #ff8ab2",
    borderRadius: 16,
    boxShadow: "0 12px 28px rgb(15 23 42 / 0.1)",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: 10,
    maxWidth: 520,
    minHeight: 120,
    padding: 20,
    width: "100%",
  }),
  resultError: style({
    color: "#c90045",
  }),
  resultMeta: style({
    color: "#9f1239",
    fontSize: 13,
    fontWeight: 700,
    margin: 0,
  }),
  stage: style({
    alignItems: "center",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: 20,
    minHeight: 300,
    padding: 32,
  }),
  stageGuide: style({
    color: "#9f1239",
    fontSize: 14,
    fontWeight: 700,
    margin: 0,
    textAlign: "center",
  }),
};
