import { style } from "@vanilla-extract/css";

export const reactFetchDevtoolsObserveAndMockContainerCss = {
  callButton: style({
    ":hover": {
      borderColor: "#ff0558",
      color: "#ff0558",
    },
    background: "#ffffff",
    border: "1px solid #ff8ab2",
    borderRadius: 999,
    color: "#c90045",
    cursor: "pointer",
    font: "inherit",
    fontSize: 14,
    fontWeight: 700,
    padding: "7px 14px",
  }),
  callRow: style({
    display: "flex",
    flexWrap: "wrap",
    gap: 12,
    justifyContent: "center",
  }),
  contentCard: style({
    background: "#fff1f5",
    border: "1px solid rgb(255 5 88 / 0.18)",
    borderRadius: 12,
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: 12,
    width: 132,
  }),
  contentGrid: style({
    display: "flex",
    flexWrap: "wrap",
    gap: 12,
    justifyContent: "center",
  }),
  contentMeta: style({
    color: "#6b7280",
    fontSize: 12,
    margin: 0,
  }),
  contentTitle: style({
    color: "#111827",
    fontSize: 14,
    fontWeight: 800,
    margin: 0,
  }),
  emptyText: style({
    color: "#9f1239",
    fontSize: 14,
    fontWeight: 700,
    margin: 0,
    padding: 24,
    textAlign: "center",
  }),
  errorMessage: style({
    color: "#111827",
    fontSize: 14,
    margin: 0,
    textAlign: "center",
  }),
  errorTitle: style({
    color: "#c90045",
    fontSize: 15,
    fontWeight: 800,
    margin: 0,
    textAlign: "center",
  }),
  friendName: style({
    color: "#111827",
    fontSize: 14,
    fontWeight: 700,
  }),
  friendRating: style({
    color: "#c90045",
    fontSize: 14,
    fontWeight: 800,
  }),
  friendRow: style({
    alignItems: "center",
    borderBottom: "1px solid #fde3ec",
    display: "flex",
    justifyContent: "space-between",
    padding: "10px 4px",
  }),
  loadingText: style({
    color: "#9f1239",
    fontSize: 14,
    fontWeight: 700,
    margin: 0,
    padding: 24,
    textAlign: "center",
  }),
  posterBox: style({
    alignItems: "center",
    background: "linear-gradient(135deg, #ff8ab2, #ff0558)",
    borderRadius: 8,
    color: "#ffffff",
    display: "flex",
    fontSize: 28,
    fontWeight: 800,
    height: 96,
    justifyContent: "center",
  }),
  stage: style({
    alignItems: "center",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: 20,
    minHeight: 300,
    padding: 32,
  }),
  stageGuide: style({
    color: "#9f1239",
    fontSize: 14,
    fontWeight: 700,
    margin: 0,
    textAlign: "center",
  }),
  totalText: style({
    color: "#6b7280",
    fontSize: 12,
    margin: 0,
    textAlign: "right",
  }),
  viewCard: style({
    background: "#ffffff",
    border: "2px solid #ff8ab2",
    borderRadius: 16,
    boxShadow: "0 12px 28px rgb(15 23 42 / 0.1)",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: 10,
    maxWidth: 520,
    minHeight: 140,
    padding: 20,
    width: "100%",
  }),
};
