import { style } from "@vanilla-extract/css";

export const reactStableRefCallbackAvoidNullOnRerenderContainerCss = {
  card: style({
    background: "#ffffff",
    border: "2px solid #ff8ab2",
    borderRadius: 16,
    boxShadow: "0 12px 28px rgb(15 23 42 / 0.1)",
    boxSizing: "border-box",
    display: "flex",
    flex: "1 1 220px",
    flexDirection: "column",
    gap: 12,
    maxWidth: 320,
    minHeight: 180,
    padding: 20,
  }),
  cardTitle: style({
    color: "#c90045",
    fontSize: 15,
    fontWeight: 800,
    margin: 0,
  }),
  logItem: style({
    listStyle: "none",
  }),
  logList: style({
    color: "#111827",
    display: "flex",
    flexDirection: "column",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: 12,
    gap: 4,
    margin: 0,
    maxHeight: 120,
    overflow: "auto",
    padding: 0,
  }),
  stage: style({
    alignItems: "center",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: 20,
    minHeight: 320,
    padding: 32,
  }),
  stageGuide: style({
    color: "#9f1239",
    fontSize: 14,
    fontWeight: 700,
    margin: 0,
    textAlign: "center",
  }),
  target: style({
    alignItems: "center",
    background: "rgb(255 5 88 / 0.08)",
    border: "1px dashed #ff8ab2",
    borderRadius: 12,
    color: "#111827",
    display: "flex",
    fontWeight: 600,
    justifyContent: "center",
    minHeight: 48,
    padding: "12px 16px",
  }),
  targets: style({
    display: "flex",
    flexWrap: "wrap",
    gap: 16,
    justifyContent: "center",
    width: "100%",
  }),
};
